name: Publish Docker

on:
  push:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/webdelin/nestjs-mongodb-restapi-ts/nestjs-mongodb-restapi-ts
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"